name: Soft T UE System Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build System
        run: |
          sudo ./scripts/install-open5gs.sh && sudo ./scripts/install-gnb.sh && sudo ./scripts/install-ue.sh

      - name: Clean UE
        run: |
          sudo ./scripts/headless-test.sh

      - name: CQI Manipulation
        run: |
          sudo ./scripts/headless-test.sh --phy.cqi_max 100 --phy.cqi_fixed 100

      - name: SDU Fuzzing RRC Setup Request
        run: |
          sudo ./scripts/headless-test.sh --rrc.sdu_fuzzed_bits 0 --rrc.fuzz_target_message "rrcSetupRequest"

      - name: SDU Fuzzing RRC Setup Complete
        run: |
          sudo ./scripts/headless-test.sh --rrc.sdu_fuzzed_bits 0 --rrc.fuzz_target_message "rrcSetupComplete"
